### ISSUE TITLE
help, how to install this plugin in wondows 7

### ISSUE THREAD

**Issue by sahroni61212** [amannocci/kibana-plugin-metric-percent#10]
i m using Kibana 5.4.0 on Windows 7.
please help me, how to install this plugin?

**Comment by amannocci** [comment]
If you want to install this plugin using kibana-plugin you can follow those steps :

Create a new directory kibana
In this new directory create a new one metric_percent_vis
In this new directory extract the git archive or execute a git clone
Now create a new archive that contains the directory kibana
You have now an archive with kibana/metric_percent_vis/content_of_archive
You can now run ./kibana-plugin install file://....

**Comment by amannocci** [comment]
I will consider this issue as solved.

**Comment by sahroni61212** [comment]
hi, sorry,,,
i want try this step but i get an error "Plugin installation was unsuccessful due to error "No kibana plugins found in archive""
