### ISSUE TITLE
No kibana plugins found in archive

### ISSUE THREAD

**Issue by macadminrohit** [amannocci/kibana-plugin-metric-percent#2]
I am running kibana 5.5 and got this error when installing this plugin

./kibana-plugin install file:///usr/share/kibana/metric_percent_vis.zip
Attempting to transfer from file:///usr/share/kibana/metric_percent_vis.zip
Transferring 91351 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by amannocci** [comment]
Hi @macadminrohit,
Unfortunately you can't use git archive as it.
If you want to install this plugin using `kibana-plugin` you can follow those steps :

1. Create a new directory  `kibana`
2. In this new directory create a new one `metric_percent_vis`
3. In this new directory extract the git archive or execute a `git clone`
4. Now create a new archive that contains the directory kibana
5. You have now an archive with `kibana/metric_percent_vis/content_of_archive`
6. You can now run `./kibana-plugin install file://....`

If you have any problem, please tell me

**Comment by macadminrohit** [comment]
Transferring 90916 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [metric_percent_vis]. Expected [5.5.1]; found [5.5.0]"

**Comment by macadminrohit** [comment]
I changed the version in package.json file and i get this output:

[root@ip-10-206-118-250 uns114]# /usr/share/kibana/bin/kibana-plugin install file:///home/uns114/kibana.zip
Attempting to transfer from file:///home/uns114/kibana.zip
Transferring 90915 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin metric_percent_vis already exists, please remove before installing a new version


Hope the plugin is not installed. How to a validate?

**Comment by macadminrohit** [comment]
[root@ip-10-206-118-250 user]# /usr/share/kibana/bin/kibana-plugin remove kibana-plugin-metric-percent
Removing kibana-plugin-metric-percent...
[root@ip-10-206-118-250 user]# /usr/share/kibana/bin/kibana-plugin list
metric_percent_vis@5.5.1
x-pack@5.5.1

**Comment by amannocci** [comment]
Try to remove `metric_percent_vis` instead of `kibana-plugin-metric-percent`.

**Comment by macadminrohit** [comment]
I deleted all the plugins and installed it again, it again installed metric_percent_vis@5.5.1

**Comment by amannocci** [comment]
That's normal, `metric_percent_vis` is the plugin name.

**Comment by macadminrohit** [comment]
I think this plugin messed with my kibana , i restarted it and it was fine, but the UI doesnt load. i get connection error on port 5601
curl -XGET http://localhost:5601
curl: (7) Failed connect to localhost:5601; Connection refused
systemd[1]: Started Kibana.
Aug 18 17:37:55 IP systemd[1]: Starting Kibana...
Aug 18 17:38:03 IP kibana[22741]: {"type":"log","@timestamp":"2017-08-18T17:38:03Z","tags":["info","optimize"],"pid":22741,"message":"Optimizing and caching bundles for kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes"}

**Comment by macadminrohit** [comment]
And i have removed all the plugins but it is not working anymore

**Comment by amannocci** [comment]
When you have this message => ` {"type":"log","@timestamp":"2017-08-18T17:38:03Z","tags":["info","optimize"],"pid":22741,"message":"Optimizing and caching bundles for kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes"}` you have to wait a moment before you can use Kibana.
This operation can be very slow.

**Comment by macadminrohit** [comment]
How long should i wait? Do i need to restart the server? Usually restart kibana daily and it doesnt take this much time and i dont see any logs being created in /var/log/kibana

**Comment by macadminrohit** [comment]
Thanks i see it up and running again, Can i install the X-pack and you plugin again? Do i need to restart kibana after that?

**Comment by amannocci** [comment]
If you want to install a plugin.
Just stop your kibana, install all plugins and then restart your kibana.
You have to wait a little bit during the optimize step and after that if everything is good you can use Kibana.
The optimize step is execute only when Kibana detect some change like for example when you install a plugin if I remember.

**Comment by amannocci** [comment]
@macadminrohit Your problem is solved ?

**Comment by unreal4u** [comment]
Thanks for the above instructions! It certainly helped me install the plugin! 

Isn't there a way that this could be automatized? Or was this recently changed by Kibana? (Sorry if it's a noob question, I'm still quite new at this, my first install was last week).

Greetings.

**Comment by macadminrohit** [comment]
@amannocci Yes i was able to start kibana successfully , what i am looking from this plugin is calculating percentage of successful transactions over total transactions. I have a field "TransactionStatus" whose value could be "Success" or "Failure". i want to calculate the percentage of Success Transactions over Total. is it possible with your plugin?

**Comment by amannocci** [comment]
@unreal4u I will create a little script to create the right structure.

@macadminrohit This is the purpose of this plugin. You can follow instructions in [README](https://github.com/amannocci/kibana-plugin-metric-percent#usage) to do this.

**Comment by macadminrohit** [comment]
@amannocci I read the README but i dont see the partition option under the metric visualization.

![image](https://user-images.githubusercontent.com/26533425/29571939-4c904976-8720-11e7-8c03-29ea6bd98639.png)

**Comment by amannocci** [comment]
@macadminrohit Please check, if you select Percent Metric and not Metric.

**Comment by macadminrohit** [comment]
I dont see that visualisation option at all. I only see metric.

**Comment by amannocci** [comment]
![capture du 2017-08-22 17-17-44](https://user-images.githubusercontent.com/10237040/29572926-e9a7262a-875d-11e7-8454-25a83eb33d23.png)
If the plugin is installed and running then you will see this option.

**Comment by macadminrohit** [comment]
It says that plugin is installed, but i dont see this visualisation :(

./kibana-plugin list
metric_percent_vis@5.5.1
x-pack@5.5.1

**Comment by macadminrohit** [comment]
@amannocci anything else i can check?

**Comment by amannocci** [comment]
@macadminrohit I will try to reproduce.

**Comment by karnamonkster** [comment]
Hi,
Facing the similar issue with v5.4.1
followed these steps
    Create a new directory kibana
    In this new directory create a new one metric_percent_vis
    In this new directory extract the git archive or execute a git clone
    Now create a new archive that contains the directory kibana
    You have now an archive with kibana/metric_percent_vis/content_of_archive
    You can now run ./kibana-plugin install file://....

**Comment by amannocci** [comment]
This issue is now address => https://github.com/amannocci/kibana-plugin-metric-percent/commit/642befbc11cb4a256f94ad9e709aa0d1ce3b941f
Just follow instruction in [README](https://github.com/amannocci/kibana-plugin-metric-percent) and everything will be fine.
