### ISSUE TITLE
VisTypesRegistryError

### ISSUE THREAD

**Issue by tamisalex** [amannocci/kibana-plugin-metric-percent#3]
I've successfully installed your plugin after following the instructions issue #2, but now I'm getting an error when I start kibana and I don't know where to start. When I remove your plugin in the issue goes away. I was hoping you could provide some insight. 

I'm using Kibana 5.2.2. 

Here's a screenshot of my issue.

![image](https://user-images.githubusercontent.com/5487505/30168504-9be3f1be-93b7-11e7-8c9f-a59eedafe467.png)

**Comment by amannocci** [comment]
Looks like an optimize error.
Please check logs.

**Comment by karnamonkster** [comment]
Same issue

**Comment by amannocci** [comment]
Can you provide a reproduicer and some logs ?

**Comment by daqqad** [comment]
Same issue. Kibana-5.3.1
To repro:
Install plugin using directions in readme.
Reload Kibana page in browser.

The only issue that shows up in logs is during installation:
undefined accessed the autoload lists which are no longer available via the Plugin API.Use the `ui/autoload/*` modules instead.

**Comment by amannocci** [comment]
Using a fresh install I'm not able to reproduice this issue.

**Comment by liran100** [comment]
Hi.
Someone has a solution?

**Comment by daqqad** [comment]
I ended up using a different plugin with similar functionality.
https://github.com/outbrain/ob-kb-percent.git

**Comment by liran100** [comment]
@daqqad - thanks for suggestion,
Anyway, I success install it by using speccific version. I used kibana 5.2.1 and I download the plugin of 5.2.1, maybe somewhere upper version or the last version dosent suppert old versoins,

**Comment by amannocci** [comment]
@liran100 You must use the correct tag version with the right kibana version.

**Comment by liran100** [comment]
@amannocci you right, but its not clear from reading the readme.
There written "You might need to change the kibana version in package.json according to your needs." - so, it sayed only change the version you want and it will work.

I suggest maybe change the readme and emphasize it and the sensitive install with special hierarchia(must folder kibana and within zip and etc),

thanks

**Comment by amannocci** [comment]
@liran100 This issue is now address
