### ISSUE TITLE
Metric Percent Always Showing No Result

### ISSUE THREAD

**Issue by hanzohan** [amannocci/kibana-plugin-metric-percent#4]
I already put the metric percent in my kibana but the return is always no result. but when i open table i can see my data. what can i do? 
im using kibana 5.5.0 
![1507697088567](https://user-images.githubusercontent.com/32681694/31422719-d9d211ae-ae79-11e7-84c8-fb8ba0d2f638.jpg)

**Comment by hanzohan** [comment]
THIS PLUGIN IS REALLY WORKED.  Thanks to the creator of this plugin

You just need put the _global first then you can use another filter in filter 2 and filter 3.
More details below.
![1507697745022](https://user-images.githubusercontent.com/32681694/31422911-3dec7746-ae7b-11e7-862d-fde953a16a6a.jpg)

**Comment by amannocci** [comment]
Sorry for the late response.  
In fact, you need to only put `_global` to indicate which value is global.

**Comment by hanzohan** [comment]
@amannocci thanks sir you plugin works perfectly in kibana 5.5.0
