### ISSUE TITLE
Any update on kibana-plugin-metric-percent for kibana 6.1.1?

### ISSUE THREAD

**Issue by neilc2016** [amannocci/kibana-plugin-metric-percent#6]

**Comment by amannocci** [comment]
Sorry for late response.
I will update the plugin for Kibana 6.x.x soon.

**Comment by agarwalshivam456** [comment]
@amannocci Any update for the same ?

**Comment by seanziee** [comment]
@amannocci Any update?

**Comment by dabombe** [comment]
Any update ?

**Comment by ztavlas** [comment]
Any update for kibana 6.3.0 and 6.3.1 ?
thanks.

**Comment by SamikshaJain** [comment]
any update on 6.3.0?

**Comment by vmavromatis** [comment]
Any update on 6.4?

**Comment by sahroni61212** [comment]
i want install this plugin, how to install this plugin in windows 7?

**Comment by amannocci** [comment]
I will deliver an update of this plugin for 6.x.x version until two weeks

**Comment by cyberjeff-u8t** [comment]
That would be awesome!

**Comment by smjgithub** [comment]
is the 6.x.x version still on target for release any day now?

**Comment by vmavromatis** [comment]
@smjgithub well he said 2 weeks 11 days ago so this leaves him with 3 days :P jk

**Comment by horacimacias** [comment]
@amannocci if there is anything I can help with just let me know. 
I'm not familiar with kibana plugin development but still, I tried updating package.json to 6.4.0 and building but kibana seems to get stuck at _Optimizing and caching browser bundles_
Again happy to help if possible.

**Comment by horacimacias** [comment]
thanks @amannocci! I can confirm it's working for me using 6.4.0.
