### ISSUE TITLE
Do the tools support multiple filter rules？

### ISSUE THREAD

**Issue by AddisonGao** [amannocci/kibana-plugin-metric-percent#7]
Such as filter Rule 1 and filter Rule 2 are effective at the same time in the Filter function.
I tried uses ‘and’ and ‘or’ in Filter query but did not work.
Thank you.

**Comment by AddisonGao** [comment]
THIS PLUGIN IS REALLY WORKED. Thanks to the creator of this plugin.
The usage of ‘and’ and ‘&&’ is different.
Multiple filter rules is suppored of '&&' filter method.

**Comment by amannocci** [comment]
I will consider this issue as solved.
