### ISSUE TITLE
How to define different the base number in the same Visualize?

### ISSUE THREAD

**Issue by AddisonGao** [amannocci/kibana-plugin-metric-percent#8]
How to define different the base number in the same Visualize?

**Comment by amannocci** [comment]
Hi, 
If you want to define another metric based on the same base number, you have to create another filter in addition of the first one.

**Comment by AddisonGao** [comment]
How about the different base number in the same Visualize？

**Comment by amannocci** [comment]
This plugin only support one base number per visualisation.
