### ISSUE TITLE
Instructions on how to install

### ISSUE THREAD

**Issue by goveebee** [amannocci/kibana-plugin-metric-percent#9]
Hi!

I'm afraid I don't understand the included installation instructions. Can you please clearify?

**Comment by amannocci** [comment]
Hi,
You use Kibana on Unix or Windows ?

**Comment by goveebee** [comment]
Hi, Linux (Ubuntu).

**Comment by amannocci** [comment]
You want to use it in a docker container or in a standalone installation ?

**Comment by goveebee** [comment]
Stand alone installation.

**Comment by amannocci** [comment]
First you can check that Kibana is in your path:
```bash
which kibana-plugin
```

And then just run this command:
```bash
bash <(curl -Ss https://raw.githubusercontent.com/amannocci/kibana-plugin-metric-percent/master/scripts/setup-plugin.sh)
```

**Comment by amannocci** [comment]
I will consider this issue as solved.
Feel free to reopen it if you have any problem.
